version: "3.7"
services:
  db:
    image: mariadb:10.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: labeeb
      MYSQL_USER: labeeb
      MYSQL_PASSWORD: labeeb
    ports:
      - 3306:3306
    # volumes:
      # - dbdata:/var/lib/mysql
  
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080

volumes:
  dbdata: